### ISSUE TITLE
Seen Marked as Invalid Value

### ISSUE THREAD

**Issue by darkn3rd** [smoeding/puppet-debconf#7]
When I attempt:

```puppet
  debconf { 'oracle-license-seen':
    package => 'oracle-java8-installer',
    item    => 'shared/accepted-oracle-license-v1-1',
    type    => 'seen',
    value   => 'true',
  }
```

I get:

```bash
Error: Parameter type failed on Debconf[oracle-license-seen]: Invalid value "seen". 
Valid values are string, boolean, select, multiselect, note, text, password, title. (file: /vagrant/site/dk_oracle_java/manifests/install.pp, line: 40)
```

Expected this to work, as man pages show this is a valid type:

```bash
 # Override default frontend to readline, but allow user to select.
debconf debconf/frontend select readline
debconf debconf/frontend seen false
```

* **Source**: http://manpages.ubuntu.com/manpages/xenial/man1/debconf-set-selections.1.html

**Comment by smoeding** [comment]
According to the manpage https://manpages.debian.org/jessie/debconf-doc/debconf-devel.7.en.html the `seen` attribute is stored as flag with the specific value and not really a value itself. I did not implement the `seen` type because it is not listed. The manpage you reference shows the debconf program and how it tries to present an interface that allows setting the `seen` value. In my opinion it is not the best soluton to present the `seen` flag as an individual type. Therefore I would rather not update the Puppet to allow the code you suggest.

You are right, the Puppet type currently does not support setting the `seen` flag. Since it is a flag (and there can be more flags), I would rather keep it together with the value. I am thinking about two implementation alternatives:

1. Only implement the `seen` flag. This would lead to:

```
debconf { 'oracle-license-select':
  package => 'oracle-java8-installer',
  item    => 'shared/accepted-oracle-license-v1-1',
  type    => 'select',
  value   => 'true',
  seen    => true,  
}
```

2. Allow arbitrary flags. This could look like this:

```
debconf { 'oracle-license-select':
  package => 'oracle-java8-installer',
  item    => 'shared/accepted-oracle-license-v1-1',
  type    => 'select',
  value   => 'true',
  flags   => { 'seen' => true, },  
}
```

I will think about an implementation.

**Comment by darkn3rd** [comment]
Is this a hack or shortcut with the debconf-set-selections then?  

I originally came across this pattern with:

* https://askubuntu.com/questions/190582/installing-java-automatically-with-silent-option

Also, it seems Ansible debconf followed the hack style, 
* https://github.com/ansible/ansible-modules-extras/issues/2456
* https://github.com/ansible/ansible-modules-extras/commit/a28d7a00b899e88d9d0b349939ae85f18052bf5c

I like your proposal for the solution better.  In the interim, I have to resort to exec with debconf.

**Comment by smoeding** [comment]
I think the debconf-set-selections interface is simple: simple to parse and simple to generate input for. It is made for shell scripts. I would rather not copy the interface as Puppet provides a much richer language to express something. Internally the type still uses the `debconf-set-selections` executable because that is the interface provided by Debian. But I would like to hide that implementation detail.

I have updated the module and it looks good in my tests. Maybe you would like to check if that would work for your case too? You only need to copy the `lib` directory including all subdirectories and files over you installed module the get the updated file. The `debconf` type now implements an additional `seen` parameter that can be set to a boolean `true` or `false` to set the flag (see my first example in my previous comment).

**Comment by smoeding** [comment]
Version 2.2.0 of the `debconf` package (available on the Puppet Forge) has an implementation of the seen property. So now you can use the following code to set the value and the seen flag at the same time:

```
debconf { 'oracle-license-select':
  package => 'oracle-java8-installer',
  item    => 'shared/accepted-oracle-license-v1-1',
  type    => 'select',
  value   => 'true',
  seen    => true,  
}
```
